before_script:
  - python -V  # Print out python version for debugging
  - pip install toml
  - git config --global user.email "wxdwfc@gmail.com"
  - git config --global user.name "wxd"
  - git submodule sync
  - git submodule update --init

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  tags:
  - rdma

  script:
    - ./magic.py config -f  build-config.toml 
    - cmake .; make boost;
  cache:
    paths:
        - ./deps/boost/

# run tests using the binary built before
test_xml:
  stage: test
  tags:
  - rdma
  script:
    - cd x_ml; ./test.sh

test_xcomm:
  stage: test
  tags:
  - rdma

  script:
    - cd xcomm; ./test.sh

