before_script:
  - python -V  # Print out python version for debugging
  - pip install toml

build:
  stage: build
  tags: 
  - rdma
  script:
    - ./magic.py config -f build-config.toml

# run tests using the binary built before
test:
  stage: test
  tags:
  - rdma
  script:
    - ./x_ml/test.sh
