before_script:
  - python -V  # Print out python version for debugging
  - pip install toml
  - git config --global user.email "wxdwfc@gmail.com"
  - git config --global user.name "wxd"
  - git submodule sync
  - git submodule update --init

build:
  stage: build
  tags: 
  - rdma
  script:
    - ./magic.py config -f build-config.toml
    - cmake .; make boost;

# run tests using the binary built before
test:
  stage: test
  tags:
  - rdma
  script:
    - cd x_ml; ./test.sh
