[[pass]]
host = "val15"
path = "/cock/fstore"
cmd = "sleep 1; ./fserver -db_type ycsbh --threads 24 --id 0 -ycsb_num=20000000"

[[pass]]
host = "val1"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 1 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val2"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 2 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val3"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 3 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val4"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 4 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val5"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 5 -total_accts=20000000 -need_hash=true"


[[pass]]
host = "val6"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 6 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val7"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 7 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val8"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 8 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val9"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 9 -total_accts=20000000 -need_hash=true"


[[pass]]
host = "val10"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 10 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val11"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 11 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val12"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 12 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val13"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 13 -total_accts=20000000 -need_hash=true"

[[pass]]
host = "val14"
path = "/cock/fstore"
cmd = "./micro --threads 24 -concurrency 1 -workloads rpc_get -server_host val15 -id 14 -total_accts=20000000 -need_hash=true"


[[pass]]
host = "val15"
path = "/cock/fstore"
cmd = "sleep 5; ./master -client_config cs.toml -epoch 40 -nclients 14"


