global_configs = "--hybrid_ratio=50  --tree_depth=4 --need_hash --concurrency=8 --workloads=ycsbc --total_accts=20000000  --undefok=rdma_payload,rdma_rounds,concurrency,workloads,total_accts,eval_type,tree_depth,hybrid_ratio,need_hash"

[[pass]]
host = "val0"
path = "/cock/fstore"
cmd = "sleep 1; ./fserver -db_type ycsbh --threads 24 --id 0 -ycsb_num=20000000"

[[pass]]
host="val1"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 1  --eval_type=rpc"


[[pass]]
host="val2"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 2  --eval_type=rpc"

[[pass]]
host="val3"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 3  --eval_type=rpc"

[[pass]]
host="val4"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 4  --eval_type=rpc"

[[pass]]
host="val5"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 5  --eval_type=sc"

[[pass]]
host="val6"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 6  --eval_type=sc"

[[pass]]
host="val7"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 7  --eval_type=sc"

[[pass]]
host="val8"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 8  --eval_type=sc"

[[pass]]
host="val9"
path="/cock/fstore"
cmd = "./ycsb --threads 24   -server_host val00 --id 9  --eval_type=sc"


[[pass]]
host = "val15"
path = "/cock/fstore"
cmd = "sleep 5; ./master -client_config cs.toml -epoch 40 -nclients 8"






