######################### start test apps ################################
## test apps
[[apps]]
name = "test_lr"
src = ["./tests/test_lr.cc", "../deps/r2/src/logging.cc"]
extra = ["gtest", "mkl_rt"]

########################## end test apps ################################


[externals]
## The external libs are libs which donot built/cloned by the tool
boost = { path = "../deps/boost", exports = ["boost", "boost_system", "boost_coroutine"],lib = "lib/",include="include"}
rlib = { path = "../deps", exports = [], lib = "", include = ""}
mkl = { path = "/opt/intel/mkl", exports = ["mkl_rt"],lib = "lib/intel64",include="include"}

