global_configs = "--nkeys=1000000 --threads=1 --vlen=false --len=8 --load_from_file=true --coros=1 --undefok=coros"

[[pass]]
host = "val1"
path = '/cock/xstore'
cmd  = './ycsb_server --alloc_mem_m=20480 --len=8 --nmodels=5000'

[[pass]]
host = "val0"
path = '/cock/xstore'
cmd  = './ycsb_client --addr="val01:8888" --coros 10  --client_name=1' 

[[pass]]
host = "val2"
path = '/cock/xstore'
cmd  = './ycsb_client --addr="val01:8888" --coros 10  --client_name=2' 

[[pass]]
host = "val3"
path = '/cock/xstore'
cmd  = './ycsb_client --addr="val01:8888" --coros 10  --client_name=3' 

[[pass]]
host = "val4"
path = '/cock/xstore'
cmd  = './ycsb_client --addr="val01:8888" --coros 10  --client_name=4' 

[[pass]]
host = "val5"
path = '/cock/xstore'
cmd  = './ycsb_client --addr="val01:8888" --coros 10  --client_name=5' 

